# apps/wiki-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wiki-service
  labels:
    app.kubernetes.io/name: wiki-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: wiki-service
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    {{- if .nodePort }}
    nodePort: {{ .nodePort }}
    {{- end }}
    protocol: TCP
  {{- end }}