# argocd/application-set.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wiki-service-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yijun-l/wiki-config.git'
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wiki-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true